export default resList = [
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
    {
      data: {
        id: "323615",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Indirapuram",
        areaName: "Ghaziabad",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
      },
    },
  
  ];